# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
pt:
  languageCode: pt
  contentDir: content/pt
  title: Ecologia Aplicada
  params:
    description: Site in Portuguese
  menu:
    main:
      - name: Início
        url: '#about'
        weight: 10
      - name: Equipe
        url: 'pt/people/'
        weight: 20
      - name: Blog
        url: '#posts'
        weight: 30
      - name: Projetos
        url: 'pt/project/'
        weight: 40
      - name: Videos
        url: '#videos'
        weight: 50
      - name: Publicações
        url: 'pt/publication/'
        weight: 60
      - name: Cursos
        url: courses/
        weight: 70
      - name: Contato
        url: '#contact'
        weight: 80