# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Início
    url: '#about'
    weight: 10
  - name: Equipe
    url: 'people/'
    weight: 20
  - name: Blog
    url: '#posts'
    weight: 30
  - name: Projetos
    url: 'project/'
    weight: 40
  - name: Videos
    url: '#videos'
    weight: 50
  - name: Publicações
    url: 'publication/'
    weight: 60
  - name: Cursos
    url: courses/
    weight: 70
  - name: Contato
    url: '#contact'
    weight: 80