[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.92.2"

[context]
[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"
[context.next.environment]
HUGO_ENABLEGITINFO = "true"
