---
title: "Componente de uma pesquisa científica"
author: "Felipe Melo"
date: '2021-05-24'
categories: []
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
lastmod: '2021-05-24T17:11:21-03:00'
projects: []
slug: 01_compo
subtitle: ''
summary: ''
tags: []
authors: []
---

## O que é uma pesquisa científica?

Para responder essa pergunta precisaremos refletir sobre a natureza do *fazer* científico. Nesta primeira aula, vamos discutir sobre alguns componentes básicos da pesquisa científica. Mas **ATENÇÃO**, essa disciplina não é sobre filosofia da ciência (apesar de passarmos pelo assunto) mas é a compilação de uma visão pessoal minha sobre o processo de formação de um pesquisador ou pesquisadora.

## Slides

```{r}
xaringanExtra::embed_xaringan( , ratio = "16:9")
```

## Sobre aprender ciência

Sempre gostei de entender como a ciência evolui como atividade humana; Seus erros são tão importantes quanto seus acertos e na biologia, nossa área de conhecimento, essa história é particularmente interessante. No entanto, sempre me fascinou a ciência como atividade humana mesmo. Lembro de na graduação em biologia, ter comprado o maravilhoso: "A evoloção do pensamento biológico" () de Ernst Mayr. Neste livro, o famoso paleontólogo discorre sobre como o pensamento biológico estava presente desde os filósofos da Grécia antiga, que refletiam sobre a organizaçã da natureza e até faziam taxonomia. 

